* Installation

Clone this repo and tell Chicken to install it:
: cd coati-2d
: chicken-install -s

* The game loop

First things first, lets include the egg:
: (import coati)
Next we'll be defining our /game/, in the context of Coati a /game/ is a function that returns a /game loop/. Coati will loop this function, calling it with its previous return value until it is false.
Here is a small example of a /game/:
#+BEGIN_SRC scheme
(define (game)
  (lambda (#!optional (frames 0))
    (if (= frames 100) #f
        (+ frames 1))))
#+END_SRC
First let's initialise Coati, tell it to create a window 800 by 600 pixels and give it a title:
#+BEGIN_SRC scheme
(coati:init 800 600 "Hello Coati!" #f)
#+END_SRC
Here Coati will call the /game loop/ a 100 times. Incrementing the variable /frames/ each time. First initialise the window with ~coati:init~, then pass the /game/ function to ~coati:start~. So for example ...
#+BEGIN_SRC scheme
(coati:start game)
#+END_SRC
... will open a non-fullscreen window with a dimension of 800x600, the title /Hello Coati/ and will start the previously defined game.
To close the window when the game is done use the function ~(coati:close)~.
#+BEGIN_SRC scheme
(coati:close)
#+END_SRC

Put this all together and give it a try:

#+BEGIN_SRC scheme
(import coati)

(define (game)
 (lambda (#!optional (frames 0))
   (if (= frames 100) #f
       (+ frames 1))))

(coati:init 800 600 "Hello Coati" #f)
(coati:start game)
(coati:close)
#+END_SRC

* Textures

Well that was boring! Now for something slightly less boring, getting something on screen. For that lets talk about textures.

At any given time there are two textures active in Coati. The first one is the /target/ texture, this is the texture to which everything is rendered and defaults to the screen (which is a texture in itself). The current target texture can be set with the macro ~(with-target texture body ...)~. The other texture is the texture that is used to render /from/ and must be set with ~(with-texture texture body ...)~.
The function ~(texture:clear colour)~ clears the current target texture with the specified colour. To create a colour use ~(rgb:create red green blue [alpha])~.

Let use change our previous game function to this ...
#+BEGIN_SRC scheme
(define (game)
  (lambda (#!optional (i 0))
    (texture:clear (rgb:create (* 0.01 i) 0 0))
    (if (= i 100) #f
        (+ i 1))))
#+END_SRC
Can you guess what this game function does? Exciting isn't it!

Let us see if we can top that by loading a texture using the function ~(texture:load filename)~. The most simple way of displaying a texture is making a rendering function from it using ~(texture:renderer texture [rect])~ calling the function returned by this will render the texture (or part of it) to the current active texture (the screen by default). 

Let's try:
#+BEGIN_SRC scheme
(define (game)
  (let* ((texture  (texture:load "./share/grid.png"))
         (renderer (texture:renderer texture)))
   (lambda (#!optional (i 0))
     (renderer)
     (if (= i 100) #f
         (+ i 1)))))
#+END_SRC

* Sprites

Rendering textures using a renderer might be okay for just a few textures but gets terribly inefficient after I while. To render many textures to screen it is best to use a /sprites/ in combination with a /sprite-batcher/. A /sprite-batcher/ collects multiple /sprites/ and renders them all in one go. To create a sprite-batcher use the function ~(sprite-batcher:create)~, to create a sprite use the function ~(sprite:create texture)~

* UI, printing text example

#+BEGIN_SRC scheme
  (map textbuffer `((cursor 5 5) 
		    (prn "Hello!")
		    (clear)
		    (colour ,(rgb:create 1 0 0))
		    (newline)
		    (prn "Test!")
		    (colour ,(rgb:create 1 1 0))
		    (prn "!")
		    (colour ,(rgb:create 0 1 1))
		    (prn "!")))
#+END_SRC

* Sprite batcher

A sprite-batcher batches all sprites into one draw call. Push sprites into it, then render once per frame.

#+BEGIN_SRC scheme
(let* ((texture (texture:load "img.png"))
       (sprite  (sprite:create texture))
       (batcher (sprite-batcher:create))
       (id      (sprite-batcher:push! batcher sprite (identity-matrix))))
  (lambda (#!rest _)
    (with-texture texture
      (with-camera (camera:create (vect:create 0 0) (vect:create 10 10))
        (sprite-batcher:render batcher)))
    #t))
#+END_SRC

Use ~sprite-batcher:change!~ to move a sprite each frame, ~sprite-batcher:remove!~ to remove it by id.
For animated sprites call ~sprite-batcher:update!~ once per frame before rendering.
~sprite:create-from-indices~ builds a sprite from a grid texture: ~(sprite:create-from-indices texture cols rows (list frame-index ...))~

* Camera

#+BEGIN_SRC scheme
(camera:create position size)
; e.g.
(camera:create (vect:create 5 5) (vect:create 10 10))
#+END_SRC

~with-camera~ makes a camera active for the enclosed body. Cameras can be nested.
~(window:size)~ returns the window dimensions as a vect.

* Input

Two forms: polling and events.

Polling (inside the loop):
#+BEGIN_SRC scheme
(key-down? key-left)   ; #t while key is held
#+END_SRC

Events (registered once, fired on state change):
#+BEGIN_SRC scheme
(listen-for-event `(key-down ,key-space) (lambda (key mod) (do-something)))
(listen-for-event '(mouse-move)          (lambda (pos) (display pos)))
(listen-for-event '(quit)               (lambda _ (coati:close)))
#+END_SRC

Return ~#f~ from a listener to unregister it. Remove by id with ~listener:remove!~.
Key constants: ~key-a~ ... ~key-z~, ~key-0~ ... ~key-9~, ~key-up~, ~key-down~, ~key-left~, ~key-right~, ~key-space~, ~key-escape~, ~key-return~, etc.
Mouse buttons: ~button_left~, ~button_right~, ~button_wheel-up~, ~button_wheel-down~.

* Transformations

#+BEGIN_SRC scheme
(trans:create position
              origin:   (vect:create 0 0)
              rotation: 0.0
              scale:    (vect:create 1 1)
              flip-h?:  #f
              flip-v?:  #f
              colour:   (rgb:create 1 1 1))
#+END_SRC

~origin~ is the anchor point in sprite-space units: the point on the sprite placed at ~position~, and the pivot for rotation. ~(vect:create 0 0)~ anchors at the bottom-left; ~(vect:create .5 .5)~ centers the sprite on ~position~.

~trans-change:create~ takes the same keyword arguments but only updates the ones specified:
#+BEGIN_SRC scheme
(node:change! node (trans-change:create rotation: new-rot position: new-pos))
#+END_SRC

* Nodes

Nodes form a scene graph. Each node has a transformation inherited from its parent.

#+BEGIN_SRC scheme
(let* ((root    (node:create-root))
       (batcher (sprite-batcher:create))
       (sprite  (sprite:create texture))
       (node    (spawn-node! (sprite-node batcher sprite)
                             root
                             (trans:create (vect:create 1 2)
                                           origin: (vect:create .5 .5)))))
  (node:change! node (trans-change:create rotation: 1.5))
  (node:remove! node))
#+END_SRC

Built-in specialisers: ~sprite-node~, ~node-rect~, ~node-point~, ~node-light~.
~node:bb-collide?~ and ~node:collide?~ filter a list of nodes by collision with a node.
~node:descendants~ returns all children recursively.

* Tilemaps

A tilemap calls a tile function per visible coordinate each frame.

#+BEGIN_SRC scheme
(let* ((tilemap   (tilemap:create))
       (tile-func (lambda ()
                    (lambda (coord)
                      (if (even? (coord:x coord)) sprite-a sprite-b)))))
  (with-texture texture
    (with-camera camera
      (tilemap:render tilemap #f #f tile-func))))
#+END_SRC

The tile function is a thunk returning ~(coord -> sprite | #f | (sprite: s colour: c))~.
Isometric tilemaps: ~(tilemap:create isometric?: #t)~.
Load a Tiled ~.tmx~ file with ~(open-tile-map "map.tmx")~.

* Static tilemap

Fixed-size tilemap; tiles set explicitly rather than by function.

#+BEGIN_SRC scheme
(let ((tm (static-tilemap:create)))
  (static-tilemap:set! tm (coord:create 3 4) sprite)
  (with-texture texture
    (with-camera camera
      (static-tilemap:render tm))))
#+END_SRC

* Gamemap

Composites multiple regions of a tilemap into cached render targets.

#+BEGIN_SRC scheme
(let* ((gm       (gamemap:create 3))
       (renderer (begin
                   (gamemap:add-region! gm (coord:create 0 0) (coord:create 10 10) mapping-fn)
                   (gamemap:renderer gm))))
  (renderer))
#+END_SRC

Call ~gamemap:make-dirty!~ to force a re-render of the cached regions.

* Polygons

#+BEGIN_SRC scheme
(let* ((batcher (polygon-batcher:create))
       (ids     (polygon-batcher:push! batcher
                                       (polygon:create (vect:create 0 0)
                                                       (vect:create 0 1)
                                                       (vect:create 1 0))
                                       (identity-matrix))))
  (polygon-batcher:change! batcher ids (matrix:rotate angle (identity-matrix)))
  (with-camera camera
    (with-blending trans (rgb:create 1 0 0 .5)
      (polygon-batcher:render batcher))))
#+END_SRC

* Blending

#+BEGIN_SRC scheme
(with-blending trans (rgb:create 1 1 1)   body ...)  ; alpha blended
(with-blending add   (rgb:create 1 1 1)   body ...)  ; additive
(with-blending one-one (rgb:create 1 1 1) body ...)  ; screen
#+END_SRC

* Sprite map

Named directional sprites from a single texture sheet.

#+BEGIN_SRC scheme
(let* ((sm     (sprite-map:create texture cols rows spec))
       (sprite (sprite-map:lookup sm 'chair 'north)))
  ...)
#+END_SRC

~spec~ is a list of names or ~(name w h)~ tuples for multi-tile sprites.
Directions: ~'north~, ~'south~, ~'east~, ~'west~.

* Physics

#+BEGIN_SRC scheme
(let* ((space (create-space))
       (body  (create-body space mass moment
                           position: (vect:create 0 0)
                           velocity: (vect:create 0 0)))
       (shape (create-circle-shape space body radius)))
  (space-on-collision-begin space (lambda (arbiter space) #t))
  (space-step space dt))
#+END_SRC

Shapes: ~create-circle-shape~, ~create-box-shape~, ~create-polygon-shape~.
Joints: ~create-pin-joint~, ~create-pivot-joint-with-pivot~, ~create-damped-spring~, etc.
Queries: ~space-nearest-point-query~, ~space-segment-query~, ~space-bb-query~.
Store arbitrary data on any object with ~body-userdata~, ~shape-userdata~, ~space-userdata~.

* Sound

#+BEGIN_SRC scheme
(let* ((sfx (sound:load "beep.wav"))
       (bgm (music:load "music.ogg")))
  (music:play! bgm)
  (sound:play! sfx)
  (sound:play-at! sfx source-pos listener-pos max-distance: 20.0))
#+END_SRC

~sound:play!~ and ~sound:play-at!~ accept ~loops:~ (default 0) and ~volume:~ (0.0–1.0, default 1.0).
~sound:play!~ returns a channel id; pass it to ~sound:stop!~ to stop early.
Music: ~music:pause!~, ~music:resume!~, ~music:stop!~, ~music:volume!~, ~music:playing?~, ~music:paused?~.

* Pixmap

CPU-side pixel buffer, convertible to a texture.

#+BEGIN_SRC scheme
(let* ((pm (pixmap:create 64 64)))
  (pixmap:set! pm 10 10 (rgb:create 1 0 0))
  (pixmap->texture pm))
#+END_SRC

* Events

Send custom events and listen for them by prefix match.

#+BEGIN_SRC scheme
(send-event 'player-hit 42)
(listen-for-event '(player-hit) (lambda (damage) (display damage)))
#+END_SRC

Listeners match if the event list starts with the pattern. Return ~#f~ to unregister.
~send-event-not-double~ skips if the same event is already queued.
