* Installation

To install Coati first make sure all the eggs on which it depends are installed.
: chicken-install -s sdl-base sdl-ttf opengl-glew gl-utils gl-math soil matchable
Then clone this repo and tell Chicken to install it:
: cd coati-2d
: chicken-install -s

* The game

First things first, lets include the egg:
: (use coati)
Next we'll be defining our /game/, in the context of Coati a /game/ is a function that returns a /game loop/. Coati will loop this function, calling it with its previous return value until it is false.
Here is a small example of a /game/:
: (define (game)
:   (lambda (#!optional (frames 0))
:     (if (= frames 100) #f
:         (+ frames 1))))
Here Coati will call the /game loop/ a 100 times. Incrementing the variable /frames/ each time. To start this game the function ~coati:start~ is used. It takes 5 arguments; the /width/, /height/ and title of the window, a boolean to decide whether to make the window /fullscreen/ and the /game/ function. So for example ...
: (coati:start 800 600 "Hello Coati" #f game)
... will open a non-fullscreen window with a dimension of 800x600, the title /Hello Coati/ and will start the previously defined game.
To close the window when the game is done use the function ~coati:close~.
: (coati:close)



