(declare (uses animators
	       batcher
	       blend
	       chunk
	       drawing
	       events
	       font
	       input
	       misc
	       node
               node-pers
	       pixmap
               particles
               polygon-batcher
	       shader
	       sound
	       sprite
	       sprite-batcher
	       texture
	       tilemap
	       trans
	       window
	       ))
