(declare (uses animators
	       batcher
	       blend
	       drawing
	       events
	       font
	       input
	       misc
	       node
	       pixmap
	       resources
	       scene
	       scene-batcher
	       shader
	       sound
	       sprite
	       sprite-batcher
	       texture
	       tilemap
	       trans
	       window
	       ))
