(declare (unit input)
	 (uses primitives))

(use (prefix glfw3 fw::))

;; Keyboard events.
;; (''key-down/up/release'' key mods)
(fw::key-callback
 (lambda (window key scancode action mods)
   (cond
    ((eq? action fw::+press+)
     (send-event 'key-down key mods))
    ((eq? action fw::+release+)
     (send-event 'key-up key mods))
    ((eq? action fw::+repeat+)
     (send-event 'key-repeat key mods)))))

;; Mouse button events.
;; (''button-down/up'' button mods)
(fw::mouse-button-callback
 (lambda (window button action mods)
   (cond
    ((eq? action fw::+press+)
     (send-event 'button-down button mods))
    ((eq? action fw::+release+)
     (send-event 'button-up button mods)))))

;; Mouse movement events.
;; (''mouse-move'' vect)
(fw::cursor-position-callback
 (lambda (window x y)
   (send-event 'mouse-move (vect:create x y))))

;; Scroll wheel events.
;; (''scroll'' up/down)
(fw::scroll-callback
 (lambda (window x y)
   (send-event 'scroll (if (< y 0) 'down 'up))))

;; the unknown key
(define key-unknown -1)
;; printable keys
(define key-space 32)
(define key-apostrophe 39)
(define key-comma 44)
(define key-minus 45)
(define key-period 46)
(define key-slash 47)
(define key-0 48)
(define key-1 49)
(define key-2 50)
(define key-3 51)
(define key-4 52)
(define key-5 53)
(define key-6 54)
(define key-7 55)
(define key-8 56)
(define key-9 57)
(define key-semicolon 59)
(define key-equal 61)
(define key-a 65)
(define key-b 66)
(define key-c 67)
(define key-d 68)
(define key-e 69)
(define key-f 70)
(define key-g 71)
(define key-h 72)
(define key-i 73)
(define key-j 74)
(define key-k 75)
(define key-l 76)
(define key-m 77)
(define key-n 78)
(define key-o 79)
(define key-p 80)
(define key-q 81)
(define key-r 82)
(define key-s 83)
(define key-t 84)
(define key-u 85)
(define key-v 86)
(define key-w 87)
(define key-x 88)
(define key-y 89)
(define key-z 90)
(define key-left-bracket 91)
(define key-backslash 92)
(define key-right-bracket 93)
(define key-grave-accent 96)
(define key-world-1 161)
(define key-world-2 162)
;; function keys
(define key-escape 256)
(define key-enter 257)
(define key-tab 258)
(define key-backspace 259)
(define key-insert 260)
(define key-delete 261)
(define key-right 262)
(define key-left 263)
(define key-down 264)
(define key-up 265)
(define key-page-up 266)
(define key-page-down 267)
(define key-home 268)
(define key-end 269)
(define key-caps-lock 280)
(define key-scroll-lock 281)
(define key-num-lock 282)
(define key-print-screen 283)
(define key-pause 284)
(define key-f1 290)
(define key-f2 291)
(define key-f3 292)
(define key-f4 293)
(define key-f5 294)
(define key-f6 295)
(define key-f7 296)
(define key-f8 297)
(define key-f9 298)
(define key-f10 299)
(define key-f11 300)
(define key-f12 301)
(define key-f13 302)
(define key-f14 303)
(define key-f15 304)
(define key-f16 305)
(define key-f17 306)
(define key-f18 307)
(define key-f19 308)
(define key-f20 309)
(define key-f21 310)
(define key-f22 311)
(define key-f23 312)
(define key-f24 313)
(define key-f25 314)
(define key-kp-0 320)
(define key-kp-1 321)
(define key-kp-2 322)
(define key-kp-3 323)
(define key-kp-4 324)
(define key-kp-5 325)
(define key-kp-6 326)
(define key-kp-7 327)
(define key-kp-8 328)
(define key-kp-9 329)
(define key-kp-decimal 330)
(define key-kp-divide 331)
(define key-kp-multiply 332)
(define key-kp-subtract 333)
(define key-kp-add 334)
(define key-kp-enter 335)
(define key-kp-equal 336)
(define key-left-shift 340)
(define key-left-control 341)
(define key-left-alt 342)
(define key-left-super 343)
(define key-right-shift 344)
(define key-right-control 345)
(define key-right-alt 346)
(define key-right-super 347)
(define key-menu 348)
(define key-last key-menu)
;; mod keys
(define mod-shift #x0001)
(define mod-control #x0002)
(define mod-alt #x0004)
(define mod-super #x0008)
;; mouse buttons
(define mouse-button-1 0)
(define mouse-button-2 1)
(define mouse-button-3 2)
(define mouse-button-4 3)
(define mouse-button-5 4)
(define mouse-button-6 5)
(define mouse-button-7 6)
(define mouse-button-8 7)
(define mouse-button-last mouse-button-8)
(define mouse-button-left mouse-button-1)
(define mouse-button-right mouse-button-2)
(define mouse-button-middle mouse-button-3)
;; joystick
(define joystick-1 0)
(define joystick-2 1)
(define joystick-3 2)
(define joystick-4 3)
(define joystick-5 4)
(define joystick-6 5)
(define joystick-7 6)
(define joystick-8 7)
(define joystick-9 8)
(define joystick-10 9)
(define joystick-11 10)
(define joystick-12 11)
(define joystick-13 12)
(define joystick-14 13)
(define joystick-15 14)
(define joystick-16 15)
(define joystick-last joystick-16)
